# Generated by Django 5.2.3 on 2025-06-11 10:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_vault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='password_vault.passwordentry')),
            ],
        ),
    ]
